### ISSUE TITLE
An error in class PiplApi_Language

### ISSUE THREAD

**Issue by SmileOmsk** [piplcom/piplapis-php#4]
Here https://github.com/piplcom/piplapis-php/blob/master/src/piplapis/data/fields.php#L1070

Now 
`$this->$region = $region;`

Must be 
`$this->region = $region;`

**Comment by yuri1992** [comment]
@SmileOmsk Thanks!
I will fix it ASAP.

**Comment by yuri1992** [comment]
https://github.com/piplcom/piplapis-php/commit/a3f37ddeb744b7390bce8e12b71009576ea3ab00
