### ISSUE TITLE
PIPL API 5 Support?

### ISSUE THREAD

**Issue by yooper** [piplcom/piplapis-php#5]
Hello,

When will this library be updated to support PIPL's API v5?

Thanks,

**Comment by yuri1992** [comment]
its already support API v5

**Comment by yooper** [comment]
You probably should update this line in your code to reflect support for version 5, 
https://github.com/piplcom/piplapis-php/blob/master/src/piplapis/data/utils.php#L8

**Comment by glerinsonum** [comment]
@yooper Hello Brother. 

Where will do execute this request php 
from command line using php or from web browser. 

<?php

require_once './piplapis/search.php';

$request = new PiplApi_SearchAPIRequest(array('email' => 'clark.kent@example.com'));
$response = $request->send();
