### ISSUE TITLE
Library is incompatible with php 7.2

### ISSUE THREAD

**Issue by roykesserwani** [piplcom/piplapis-php#6]
create_function() is deprecated in php 7.2+
Your containers.php class, line 342, had thrown off an error in my application when I upgraded php version.

**Comment by billytd** [comment]
I'm experiencing the same deprecation error.

**Comment by roykesserwani** [comment]
Checkout my repo, I got a composer package that fixes this problem

**Comment by rjhallsted** [comment]
Submitted a fix with PR #10
